version: '3.3'
services:
  db1:
    image: mysql:5.7
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db1'
      MYSQL_USER: 'user1'
      MYSQL_PASSWORD: 'pass1'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
  db2:
    image: mysql:5.7
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db2'
      MYSQL_USER: 'user2'
      MYSQL_PASSWORD: 'pass2'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3307:3306'